### ISSUE TITLE
Deprecate this library

### ISSUE THREAD

**Issue by djmitche** [taskcluster/azure-entities#188]
We (taskcluster) don't use this anymore, and https://www.npmjs.com/package/azure-entities suggests that nobody does.

Opinions on deprecating it?  @imbstack? @jwhitlock?

It's a reversible thing, so if someone complains we can always start supporting it again.

**Comment by djmitche** [comment]
(The same would apply for azure-blob-storage; I think fast-azure-storage actually *does* have users, so we can leave that)

**Comment by jwhitlock** [comment]
Last non-dependency PR was over a year ago: https://github.com/taskcluster/azure-entities/pull/91.
I support deprecating it.

**Comment by djmitche** [comment]
Done!
